channels:
  - defaults
dependencies:
  - numpy>=1.16.5
  - scipy
  - pandas
  - scikit-learn
  - seaborn
  - ipywidgets
  - sphinx
  - sphinx_rtd_theme
  - pytest
  - pytest-cov
  - pip
  - pip:
    - coveralls
